# Generated by Django 4.0.3 on 2022-05-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0018_seat_pepsi_seat_popcorn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='pepsi',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='popcorn',
            field=models.PositiveIntegerField(),
        ),
    ]
