# Generated by Django 4.0.3 on 2022-05-24 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0020_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='pepsi',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='popcorn',
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popcorn', models.PositiveIntegerField()),
                ('pepsi', models.PositiveIntegerField()),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplex.movie')),
            ],
        ),
    ]
