# Generated by Django 4.0.3 on 2022-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0021_remove_seat_pepsi_remove_seat_popcorn_snack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
