# Generated by Django 4.0.3 on 2022-05-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0022_alter_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pepsi',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='popcorn',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
