# Generated by Django 4.0.3 on 2022-05-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0023_booking_pepsi_booking_popcorn'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
